[CAL-2115] Feature/create task planner UI/cal 2115
Gio481/TaskPlanner pull request #1
Opened 2022-04-19 10:19 UTC by Gio481

https://spaceneobank.atlassian.net/browse/CAL-2115

2022-04-19 10:24 UTC, AnaRusadze requested changes

2022-04-19 10:24 UTC, AnaRusadze commented on app/src/main/java/com/example/taskplanner/presentation/custom_view/InputTextCustomView.kt
> +        LayoutInflater.from(context), this, true)
ჯობია, რომ ვიუს და მის ბაინდინგს მსგავსი სახელი ერქვათ

2022-04-19 10:24 UTC, AnaRusadze commented on app/src/main/java/com/example/taskplanner/presentation/custom_view/InputTextCustomView.kt
> +        private const val PASSWORD_TOGGLE_BUTTON_COLOR = "#004481"
ფერების რესურსში დაამატე

2022-04-19 10:24 UTC, AnaRusadze commented on app/src/main/java/com/example/taskplanner/presentation/custom_view/ProjectStatesCustomView.kt
> +        private const val TODO_STATE_COLOR = "#4CABCE"
ესეც

2022-04-19 10:33 UTC, Gio481 commented on app/src/main/java/com/example/taskplanner/presentation/custom_view/InputTextCustomView.kt
> +        LayoutInflater.from(context), this, true)
done

2022-04-19 10:34 UTC, Gio481 commented on app/src/main/java/com/example/taskplanner/presentation/custom_view/InputTextCustomView.kt
> +        private const val PASSWORD_TOGGLE_BUTTON_COLOR = "#004481"
ეს გატანილი მაქვს ფერების რესურსებში, პროსტა ამ შემთხვევაში სტრინგად უნდა გადავცე და მაგიტო მაქვს ასე

2022-04-19 12:41 UTC, AnaRusadze requested changes

2022-04-19 12:41 UTC, AnaRusadze commented on app/src/main/java/com/example/taskplanner/presentation/custom_view/InputTextCustomView.kt
> +        private const val PASSWORD_TOGGLE_BUTTON_COLOR = "#004481"
ეს ფუნქცია არ გაქვს გამოყენებული, რისთვისაა? ქოლორის პარსვის ნაცვლად შეგიძლია ფერის კონტექსით ამოღება ContextCompat.getColor(context, R.color.white)) -> მაგალითად

2022-04-19 12:41 UTC, AnaRusadze commented on app/src/main/java/com/example/taskplanner/presentation/custom_view/InputTextCustomView.kt
> +        setTextInputEditTextAttributes(typedArray)
ჯობია, რომ ფუნქციებში ტაიპდ ერეის მაგივრად თვითონ ის სტრინგი/ინტი/ ნებისმიერი ამოღებული მნიშვნელობა გადასცე, რომელსაც გამოიყენებ და ტაიპდერეიდან რესურსების ამოღება ერთ ადგილას გააკეთო, ინიტში კაი ვარიანტია

2022-04-26 11:31 UTC, GiorgiMamagulashvil1 commented on app/src/main/java/com/example/taskplanner/presentation/ui/home/HomeFragment.kt
> +    override val bindingInflater: (inflater: LayoutInflater, container: ViewGroup?, attachRoot: Boolean) -> FragmentHomeBinding
ეს პარამეტრები ფრაგმენტს არ სჭირდება და არ უნდა ხედავდეს

2022-04-26 12:49 UTC, Gio481 commented on app/src/main/java/com/example/taskplanner/presentation/ui/home/HomeFragment.kt
> +    override val bindingInflater: (inflater: LayoutInflater, container: ViewGroup?, attachRoot: Boolean) -> FragmentHomeBinding
რატო ?

2022-04-27 05:53 UTC, merged

2022-04-27 05:53 UTC, Gio481 commented on app/src/main/java/com/example/taskplanner/presentation/custom_view/InputTextCustomView.kt
> +        private const val PASSWORD_TOGGLE_BUTTON_COLOR = "#004481"
done