[CAL-2180] Feature/configure project and task screens/cal 2180
Gio481/TaskPlanner pull request #10
Opened 2022-05-17 20:08 UTC by Gio481

https://spaceneobank.atlassian.net/browse/CAL-2180

2022-05-18 07:35 UTC, AnaRusadze requested changes

2022-05-18 07:35 UTC, AnaRusadze commented on app/src/main/java/com/example/taskplanner/presentation/ui/project/details/ProjectDetailsFragment.kt
> +                projectEndInTimeTextView.countDownTimer.start()
ჯობია, რომ countdownTimer private ცვლადი იყოს და ქასთუმ ვიუში იყოს ფაბლიქ სტარტის ფუნქცია, სადაც თაიმერს დასტარტავ და ამ ფუნქციით მიწვდები.

კიდევ აიდიში ტექსტვიუს სახელი თაიმერვიუთი შეცვალე

2022-05-18 07:35 UTC, AnaRusadze commented on app/src/main/java/com/example/taskplanner/util/HelperFunctions.kt
> +    val endDate = "${end2.formatDate()} 23:59:00"
23:59:00 es ristvis?

2022-05-18 08:41 UTC, Gio481 commented on app/src/main/java/com/example/taskplanner/util/HelperFunctions.kt
> +    val endDate = "${end2.formatDate()} 23:59:00"
რისთვის და დრო რო დღის ბოლომდეა

2022-05-18 08:51 UTC, Gio481 commented on app/src/main/java/com/example/taskplanner/presentation/ui/project/details/ProjectDetailsFragment.kt
> +                projectEndInTimeTextView.countDownTimer.start()
done

2022-05-18 09:20 UTC, AleksandreGalogreBaramidze approved these changes

2022-05-18 16:26 UTC, GiorgiMamagulashvil1 requested changes

2022-05-18 16:26 UTC, GiorgiMamagulashvil1 commented on app/src/main/java/com/example/taskplanner/presentation/custom_view/TimerCustomView.kt
> +                val daysInMilli = hoursInMilli * 24
const ცვლადები ჯობია იყოს ეს ინტეჯერები

2022-05-18 16:26 UTC, GiorgiMamagulashvil1 commented on app/src/main/java/com/example/taskplanner/presentation/ui/project/details/ProjectDetailsFragment.kt
> +                projectProgressButton.setTextColor(ContextCompat.getColor(requireContext(),
ექსთენშენი გააკეთე setTextColor ის

2022-05-18 16:26 UTC, GiorgiMamagulashvil1 commented on app/src/main/java/com/example/taskplanner/presentation/ui/project/details/actions/ProjectActionsBottomSheetFragment.kt
> +            binding.createNewsTaskCustomView.setOnClickListener {
binding არ სჭირდება მგონი აქ

2022-05-18 16:26 UTC, GiorgiMamagulashvil1 commented on app/src/main/java/com/example/taskplanner/presentation/ui/task/details/TaskDetailsFragment.kt
> +                taskStateButton.setBackgroundColor(ContextCompat.getColor(requireContext(),
ამის ექსთენშენიც კარგი იქნება

2022-05-18 16:26 UTC, GiorgiMamagulashvil1 commented on app/src/main/java/com/example/taskplanner/presentation/ui/task/details/TaskDetailsFragment.kt
> +            setBackgroundColor(ContextCompat.getColor(requireContext(), progress.color))
აქაც

2022-05-18 16:26 UTC, GiorgiMamagulashvil1 commented on app/src/main/java/com/example/taskplanner/util/extensions/FragmentExtensions.kt
> +        setTitleText("Select Date")
სტრინგები გაიტანე ეს

2022-05-18 16:26 UTC, GiorgiMamagulashvil1 commented on app/src/main/java/com/example/taskplanner/util/extensions/LongExtensions.kt
> +    val sdf = SimpleDateFormat("MMM dd yyyy", Locale.getDefault())
ეს სტრინგი სტრინგებში გაიტანე ან კონსტანტური ცვლადი გააკეთე

2022-05-18 16:26 UTC, GiorgiMamagulashvil1 commented on app/src/main/res/layout/fragment_project_bottom_sheet.xml
> +        app:actionName="Create New Task"
ეს სტრინგებში გააგდე

2022-05-18 16:26 UTC, GiorgiMamagulashvil1 commented on app/src/main/res/layout/fragment_project_bottom_sheet.xml
> +        app:actionName="Update"
ესეც

2022-05-18 16:26 UTC, GiorgiMamagulashvil1 commented on app/src/main/res/layout/fragment_project_bottom_sheet.xml
>          app:actionName="Delete Project"
ესეც

2022-05-19 00:09 UTC, Gio481 commented on app/src/main/java/com/example/taskplanner/presentation/ui/project/details/ProjectDetailsFragment.kt
> +                projectProgressButton.setTextColor(ContextCompat.getColor(requireContext(),
done

2022-05-19 00:09 UTC, Gio481 commented on app/src/main/java/com/example/taskplanner/presentation/ui/task/details/TaskDetailsFragment.kt
> +                taskStateButton.setBackgroundColor(ContextCompat.getColor(requireContext(),
done

2022-05-19 00:09 UTC, Gio481 commented on app/src/main/java/com/example/taskplanner/presentation/ui/task/details/TaskDetailsFragment.kt
> +            setBackgroundColor(ContextCompat.getColor(requireContext(), progress.color))
done

2022-05-19 00:12 UTC, Gio481 commented on app/src/main/java/com/example/taskplanner/util/extensions/FragmentExtensions.kt
> +        setTitleText("Select Date")
done

2022-05-19 00:16 UTC, Gio481 commented on app/src/main/java/com/example/taskplanner/presentation/custom_view/TimerCustomView.kt
> +                val daysInMilli = hoursInMilli * 24
done

2022-05-19 00:17 UTC, Gio481 commented on app/src/main/java/com/example/taskplanner/presentation/ui/project/details/actions/ProjectActionsBottomSheetFragment.kt
> +            binding.createNewsTaskCustomView.setOnClickListener {
done

2022-05-19 00:23 UTC, Gio481 commented on app/src/main/java/com/example/taskplanner/util/extensions/LongExtensions.kt
> +    val sdf = SimpleDateFormat("MMM dd yyyy", Locale.getDefault())
done

2022-05-19 00:25 UTC, Gio481 commented on app/src/main/res/layout/fragment_project_bottom_sheet.xml
>          app:actionName="Delete Project"
done

2022-05-19 00:25 UTC, Gio481 commented on app/src/main/res/layout/fragment_project_bottom_sheet.xml
> +        app:actionName="Update"
done

2022-05-19 00:25 UTC, Gio481 commented on app/src/main/res/layout/fragment_project_bottom_sheet.xml
> +        app:actionName="Create New Task"
done

2022-05-19 03:51 UTC, GiorgiMamagulashvil1 approved these changes

2022-05-19 05:30 UTC, gioqemoklidze approved these changes

2022-05-19 05:31 UTC, merged