[CAL-2119] Feature/fetch data from repositories/cal 2119
Gio481/TaskPlanner pull request #4
Opened 2022-04-28 00:10 UTC by Gio481

https://spaceneobank.atlassian.net/browse/CAL-2119

2022-04-28 08:18 UTC, GiorgiMamagulashvil1 requested changes

2022-04-28 08:18 UTC, GiorgiMamagulashvil1 commented on app/src/main/java/com/example/taskplanner/presentation/ui/auth/signin/viewmodel/SignInViewModel.kt
> +    val errorLiveData: LiveData<String> = _errorLiveData
ერთი LiveData გააკეთე ცალ-ცალკე რომ არ აობზერვო ეს ორი სტეიტი

2022-04-28 08:18 UTC, GiorgiMamagulashvil1 commented on app/src/main/java/com/example/taskplanner/presentation/ui/task/create/viewmodel/TaskCreatorViewModel.kt
> +            taskCreatorUseCase.createTask(projectId = projectId, taskDomain = taskDomain)
ვალიდაციები არ სჭირდება ამ პარამეტრებს?

2022-04-28 09:12 UTC, Gio481 commented on app/src/main/java/com/example/taskplanner/presentation/ui/task/create/viewmodel/TaskCreatorViewModel.kt
> +            taskCreatorUseCase.createTask(projectId = projectId, taskDomain = taskDomain)
მაგის განსაზღვრას შემდეგ ბრენჩზე ვაპირებ

2022-04-29 08:39 UTC, AleksandreGalogreBaramidze approved these changes

2022-04-29 08:54 UTC, AnaRusadze approved these changes

2022-04-29 08:54 UTC, merged