[CAL-2120] Feature/add some features/cal 2120
Gio481/TaskPlanner pull request #5
Opened 2022-04-29 16:50 UTC by Gio481

https://spaceneobank.atlassian.net/browse/CAL-2120

2022-05-02 09:07 UTC, GiorgiMamagulashvil1 requested changes

2022-05-02 09:07 UTC, GiorgiMamagulashvil1 commented on app/src/main/java/com/example/taskplanner/data/mapper/UserDtoMapper.kt
> +            profileImage = model.profileImage
with(model)

2022-05-02 09:07 UTC, GiorgiMamagulashvil1 commented on app/src/main/java/com/example/taskplanner/presentation/ui/auth/signup/validator/SignUpValidatorImpl.kt
> +        private const val PASSWORD_MATH_ERROR = "passwords do not match"
სტრინგებში გაიტანე ესენი

2022-05-02 09:07 UTC, GiorgiMamagulashvil1 commented on app/src/main/java/com/example/taskplanner/presentation/ui/auth/signup/validator/SignUpValidatorImpl.kt
> +class SignUpValidatorImpl : SignUpValidator {
ყველა ფიჩას თავისი ვალიდატორი უნდა ქონდეს?

2022-05-02 09:07 UTC, GiorgiMamagulashvil1 commented on app/src/main/java/com/example/taskplanner/presentation/ui/project/create/validator/ProjectValidatorImpl.kt
> +class ProjectValidatorImpl : ProjectValidator {
რამე გლობალური ვალიდაცია გააკეთე, არაა საჭირო სათითაოდ ამდენი იმპლემენტაციები ყველა ფიჩაზე

2022-05-02 09:55 UTC, Gio481 commented on app/src/main/java/com/example/taskplanner/presentation/ui/project/create/validator/ProjectValidatorImpl.kt
> +class ProjectValidatorImpl : ProjectValidator {
ახალი რამე რო დაემატოს მაგალითად პროექტის შექმანს, მარტო პროექტის ვალიდატორში შევცვლი და ეგრე სხვებზეც

2022-05-02 13:38 UTC, Gio481 commented on app/src/main/java/com/example/taskplanner/presentation/ui/auth/signup/validator/SignUpValidatorImpl.kt
> +class SignUpValidatorImpl : SignUpValidator {
კი, მასე ჩავთვალე სწორად

2022-05-03 18:24 UTC, Gio481 commented on app/src/main/java/com/example/taskplanner/data/mapper/UserDtoMapper.kt
> +            profileImage = model.profileImage
done

2022-05-03 18:26 UTC, Gio481 commented on app/src/main/java/com/example/taskplanner/presentation/ui/auth/signup/validator/SignUpValidatorImpl.kt
> +        private const val PASSWORD_MATH_ERROR = "passwords do not match"
Toast რო მაქვს იმას სტრინგად ვაწვდი ტექსტს და აქ ინტს ხო მექნება და მაშინ კონტექსტის დაჭერა მომიწევს ამ კლასში და კონსტანდებად რო იყოს აჯობებს

2022-05-03 22:00 UTC, gioqemoklidze commented on app/src/main/java/com/example/taskplanner/presentation/ui/auth/signup/validator/SignUpValidatorImpl.kt
> +        private const val PASSWORD_MATH_ERROR = "passwords do not match"
და სხვა ენაზე რო მოგინდეს მაგ ტოასტის გამოტანა მერე რას იზავ ? როგორ მოიქცევი ?

2022-05-03 22:07 UTC, Gio481 commented on app/src/main/java/com/example/taskplanner/presentation/ui/auth/signup/validator/SignUpValidatorImpl.kt
> +        private const val PASSWORD_MATH_ERROR = "passwords do not match"
სხვანაირად

2022-05-03 23:02 UTC, gioqemoklidze requested changes

2022-05-03 23:02 UTC, gioqemoklidze commented on app/src/main/java/com/example/taskplanner/domain/repository/auth/AuthRepository.kt
> +    suspend fun getUserInfo():Resources<UserDomain>
ესენი დაყავი

2022-05-03 23:02 UTC, gioqemoklidze commented on app/src/main/java/com/example/taskplanner/presentation/custom_view/ActionTypeCustomView.kt
> +    var actionBackground: Int? = null
ამას კოდის მხრიდან თუ არ ცვლი შეგიძლია გააფრაივათო

2022-05-03 23:02 UTC, gioqemoklidze commented on app/src/main/java/com/example/taskplanner/presentation/ui/auth/signin/viewmodel/SignInViewModel.kt
>  import androidx.lifecycle.ViewModel
unused import

2022-05-04 08:39 UTC, Gio481 commented on app/src/main/java/com/example/taskplanner/domain/repository/auth/AuthRepository.kt
> +    suspend fun getUserInfo():Resources<UserDomain>
user-ს რა ეხება ერთ რეპოზიტორში მაქვს და use case ში ვყოფ

2022-05-04 08:41 UTC, gioqemoklidze commented on app/src/main/java/com/example/taskplanner/domain/repository/auth/AuthRepository.kt
> +    suspend fun getUserInfo():Resources<UserDomain>
ეგ ვნახე რო იუსქეისში ყოფ მარა ნახე აუთჰ გიწერია და აბდეით და გეთ უზერ ინფო აუთს არ ეხება თან დაყოფილი იუსქეისები რო გაქ შესვლა რეგისტრაციას რატო უნდა ხედავდეს ან უზერის განახლება შესვლას

2022-05-04 10:53 UTC, GiorgiMamagulashvil1 commented on app/src/main/java/com/example/taskplanner/presentation/ui/auth/signup/validator/SignUpValidatorImpl.kt
> +        private const val PASSWORD_MATH_ERROR = "passwords do not match"
@Gio481  სტრინგად ამოიღე ვალიდატორშივე

2022-05-04 10:54 UTC, GiorgiMamagulashvil1 commented on app/src/main/java/com/example/taskplanner/presentation/ui/auth/signup/validator/SignUpValidatorImpl.kt
> +class SignUpValidatorImpl : SignUpValidator {
ჩემი აზრით არასწორია, ბევრი კოდის გამეორება მოგიწევს, ჯობია რამე გლობალური ვალიდატორი გქონდეს

2022-05-05 08:15 UTC, Gio481 commented on app/src/main/java/com/example/taskplanner/presentation/custom_view/ActionTypeCustomView.kt
> +    var actionBackground: Int? = null
done

2022-05-05 08:15 UTC, Gio481 commented on app/src/main/java/com/example/taskplanner/presentation/ui/auth/signin/viewmodel/SignInViewModel.kt
>  import androidx.lifecycle.ViewModel
done

2022-05-05 08:15 UTC, Gio481 commented on app/src/main/java/com/example/taskplanner/domain/repository/auth/AuthRepository.kt
> +    suspend fun getUserInfo():Resources<UserDomain>
done

2022-05-06 08:23 UTC, Gio481 commented on app/src/main/java/com/example/taskplanner/presentation/ui/auth/signup/validator/SignUpValidatorImpl.kt
> +        private const val PASSWORD_MATH_ERROR = "passwords do not match"
done

2022-05-06 14:48 UTC, GiorgiMamagulashvil1 approved these changes

2022-05-06 14:49 UTC, merged