[CAL-2179] Feature/configure auth screens/cal 2179
Gio481/TaskPlanner pull request #9
Opened 2022-05-16 14:46 UTC by Gio481

https://spaceneobank.atlassian.net/browse/CAL-2179

2022-05-16 16:21 UTC, AleksandreGalogreBaramidze approved these changes

2022-05-17 03:56 UTC, GiorgiMamagulashvil1 commented on app/src/main/java/com/example/taskplanner/presentation/ui/auth/signin/SignInFragment.kt
> +            if (it != null) {
let{}

2022-05-17 03:56 UTC, GiorgiMamagulashvil1 commented on app/src/main/java/com/example/taskplanner/presentation/ui/auth/signup/SignUpFragment.kt
> +            binding.userProfileImageView.setOnClickListener {
binding აღარ ჭირდება

2022-05-17 10:30 UTC, Gio481 commented on app/src/main/java/com/example/taskplanner/presentation/ui/auth/signin/SignInFragment.kt
> +            if (it != null) {
done

2022-05-17 10:30 UTC, Gio481 commented on app/src/main/java/com/example/taskplanner/presentation/ui/auth/signup/SignUpFragment.kt
> +            binding.userProfileImageView.setOnClickListener {
done

2022-05-17 10:31 UTC, GiorgiMamagulashvil1 approved these changes

2022-05-17 11:17 UTC, AnaRusadze approved these changes

2022-05-17 11:18 UTC, shioandghuladze requested changes

2022-05-17 11:18 UTC, shioandghuladze commented on app/src/main/java/com/example/taskplanner/presentation/custom_view/InputTextCustomView.kt
> +        return binding.textInputEditText.text.toString()
textInputEditText რატო ქვია?

2022-05-17 11:18 UTC, shioandghuladze commented on app/src/main/java/com/example/taskplanner/presentation/ui/auth/signup/SignUpFragment.kt
> +            if (it != null) {
Unit ტიპის ყოფილიყო ბარემ ლაივ დატა თუ მარტო რამე ექშენი რომ მოხდა მაგის გასაგებად იყენებ ერთხელ

2022-05-17 11:18 UTC, shioandghuladze commented on app/src/main/java/com/example/taskplanner/presentation/ui/auth/signup/SignUpFragment.kt
> +    private fun alertDialog(block: AlertDialog.Builder.() -> Unit): AlertDialog? {
ესეთი რაღაცეები ექსთენშენებში გქონდეს ხოლმე გლობალურად რაც შეიძლება დაგჭირდეს

2022-05-17 11:18 UTC, shioandghuladze commented on app/src/main/java/com/example/taskplanner/util/PermissionManager.kt
> +            hasPermission(Manifest.permission.WRITE_EXTERNAL_STORAGE) && hasPermission(Manifest.permission.READ_EXTERNAL_STORAGE) -> {
ძალიან ჩაჰარდკოდებული გაქვს ეს ფუნქცია ფაქტიურად მხოლოდ ამ ორ ფერმიშენს ასაპორტებს ყოველთვის უკეთესია გლობალური ფუნქციონალის შექმნა რომელიც ბევრ რამეზე მოერგება მითუმეტეს PermissionManager კლასი ზოგადად ფერმიშენებს უნდა ასაპორტებდეს და არა რომელიმე კონკრეტულებს

2022-05-17 11:38 UTC, Gio481 commented on app/src/main/java/com/example/taskplanner/presentation/custom_view/InputTextCustomView.kt
> +        return binding.textInputEditText.text.toString()
textInputEditText - ია და მაგიტო

2022-05-17 11:45 UTC, Gio481 commented on app/src/main/java/com/example/taskplanner/presentation/ui/auth/signup/SignUpFragment.kt
> +    private fun alertDialog(block: AlertDialog.Builder.() -> Unit): AlertDialog? {
done

2022-05-17 11:45 UTC, Gio481 commented on app/src/main/java/com/example/taskplanner/presentation/ui/auth/signup/SignUpFragment.kt
> +            if (it != null) {
done

2022-05-17 11:46 UTC, Gio481 commented on app/src/main/java/com/example/taskplanner/util/PermissionManager.kt
> +            hasPermission(Manifest.permission.WRITE_EXTERNAL_STORAGE) && hasPermission(Manifest.permission.READ_EXTERNAL_STORAGE) -> {
სახელი გადავარქვა რო ჩანდეს რა პერმიშენებს ემსახურება ?

2022-05-17 11:46 UTC, shioandghuladze commented on app/src/main/java/com/example/taskplanner/presentation/custom_view/InputTextCustomView.kt
> +        return binding.textInputEditText.text.toString()
კი მივხვდი მაგას მარა ცუდი აიდია მაინც

2022-05-17 11:49 UTC, shioandghuladze commented on app/src/main/java/com/example/taskplanner/util/PermissionManager.kt
> +            hasPermission(Manifest.permission.WRITE_EXTERNAL_STORAGE) && hasPermission(Manifest.permission.READ_EXTERNAL_STORAGE) -> {
ეგ უარესია კლასი თავის მნიშვნელობას დაკარგავს 😄 ეცადე ფერმიშენების გადაწოდების საშუალება შექმნა და გლობალურად გააკეთო ეგ ლოგიკა რა

2022-05-17 11:50 UTC, Gio481 commented on app/src/main/java/com/example/taskplanner/presentation/custom_view/InputTextCustomView.kt
> +        return binding.textInputEditText.text.toString()
არა, რატო?

2022-05-17 11:55 UTC, shioandghuladze commented on app/src/main/java/com/example/taskplanner/presentation/custom_view/InputTextCustomView.kt
> +        return binding.textInputEditText.text.toString()
დეფოლტ აიდია ეგ თუ შენ დააწერე ხელით?

2022-05-17 11:56 UTC, Gio481 commented on app/src/main/java/com/example/taskplanner/presentation/custom_view/InputTextCustomView.kt
> +        return binding.textInputEditText.text.toString()
მე დავაწერე

2022-05-17 11:57 UTC, Gio481 commented on app/src/main/java/com/example/taskplanner/presentation/custom_view/InputTextCustomView.kt
> +        return binding.textInputEditText.text.toString()
ყველა ინფუთ ტაიპზე მორგებული აიდი რო ყოფილიყო მაგ პონტში

2022-05-17 11:57 UTC, shioandghuladze commented on app/src/main/java/com/example/taskplanner/presentation/custom_view/InputTextCustomView.kt
> +        return binding.textInputEditText.text.toString()
კაი მაშინ იყოს TextInputEditText ვიჯეტია და მეგონა დეფოლტად რა აიდიც დაეწერა ის დაუტოვე

2022-05-17 12:03 UTC, Gio481 commented on app/src/main/java/com/example/taskplanner/util/PermissionManager.kt
> +            hasPermission(Manifest.permission.WRITE_EXTERNAL_STORAGE) && hasPermission(Manifest.permission.READ_EXTERNAL_STORAGE) -> {
ოქეი, მაგაზე როგორ გაწყენინებ

2022-05-17 13:09 UTC, Gio481 commented on app/src/main/java/com/example/taskplanner/util/PermissionManager.kt
> +            hasPermission(Manifest.permission.WRITE_EXTERNAL_STORAGE) && hasPermission(Manifest.permission.READ_EXTERNAL_STORAGE) -> {
done

2022-05-17 13:57 UTC, shioandghuladze approved these changes

2022-05-17 13:57 UTC, merged